# Generated by Django 2.0.3 on 2018-08-15 22:42

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0064_productvariant_handle_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chart', versatileimagefield.fields.VersatileImageField(upload_to='size-charts')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='size_chart', to='product.Category')),
                ('product_type', models.ManyToManyField(related_name='size_chart', to='product.ProductType')),
                ('products', models.ManyToManyField(related_name='size_chart', to='product.Product')),
            ],
            options={
                'permissions': (('view', 'Can view size charts'), ('edit', 'Can edit size charts')),
            },
        ),
    ]
